### PR TITLE
[Work-in-Progress] Porting USC to use MirAL instead of mirserver

### PR DESCRIPTION
**Pull request by WebDrake**
Following discussion on the message boards (https://forums.ubports.com/topic/990/organizing-unity8-work), this PR covers the complete state of my work so far on porting USC from the mirserver API to MirAL.  It's the same patches as in https://github.com/WebDrake/unity-system-compositor-yunit/pull/1 but rebased on the `bionic` branch.

This PR is not intended to be merged itself (too many patches, too many moving parts!) but can serve as a starting point for discussion on how this transition should be managed in UBPorts.  Ideally, I'd like to make these changes via multiple incremental PRs, all going through CI and whatever other testing is available.

It also means that if I vanish for any reason, the work is still here for other people's reference.

A few notes:

* the main goal of this work was to incrementally remove direct uses of the mirserver API and replace by appropriate MirAL equivalents, while (ideally) not changing behaviour in any way

* the current state of things sees a rather spaghettified `main` function.  This is a deliberate choice, to pick things apart in an incremental fashion before putting things back together in a way that suits things best for MirAL.  However, different approaches are probably possible: for example, instead of removing the old `USC::Server` class entirely, it might better be repurposed as an "own all the app resources" class with no dependency on `mir::Server`.

* the current state of things is that all the "easy" refactoring has been done and now we have to start looking at the components of USC with more subtle dependencies on `mir::server` and `mir::input`.  A summary is here: https://github.com/WebDrake/unity-system-compositor-yunit/pull/1#issuecomment-347339346

* the code as written was tested on a xenial system with the Yunit PPA, and no problems were observed, but it was never tested in phone/tablet situations, since I really didn't have the facilities to do such tests.

What I'd suggest is that UBPorts should take a first look at this coming from the point of view of (1) whether this work looks sane AT ALL and (2) if so, what the requirements and possibilities are from your side in terms of testing, code quality, and managing the transition.

I've tried to document each patch with as much detail as possible about the logic of the changes, so hope that helps.

Anyway, {enj,destr}oy.

### CODE REVIEW

**Comment by WebDrake** [comment]
At a guess, I would suppose this is failing because `libmiral-dev` is not included in the CI setup.  I don't see anything in the source tree related to that, so I assume these kind of CI dependencies are determined elsewhere ... ?

**Comment by mariogrip** [comment]
The build dependencies is defined here: https://github.com/ubports/unity-system-compositor/blob/bionic/debian/control#L5 We use the debian build system for out CI system, this simplifies things. Adding miral there to this pr should fix it.

**Comment by WebDrake** [comment]
Ah, thanks!  I'd missed that you kept the `debian/` section (Yunit ditched it).  I've tweaked the first patch accordingly.  Let's see if it improves matters.

**Comment by WebDrake** [comment]
OK, this needs a bit of a deeper look.  Any objections to me (ab)using the CI a bit with a few force-pushes if I need to?

**Comment by mariogrip** [comment]
Oh no problem at all, go ahead just push (and build) when you need to :)

**Comment by WebDrake** [comment]
Hmm, well, this is interesting: the code builds fine on my Xenial system but my Bionic system reproduces the compiler errors.  Nothing has changed AFAICT on the MirAL side of things has changed.

There seem to be 2 things needed to fix these errors:

* use `miral::pre_init` instead of just `pre_init` (fair enough, but for some reason on xenial the compiler can resolve that; maybe g++ 7 is stricter?)

* always provide a default value for `CommandLineOption` delegates that take a `bool` parameter.

Basically, the problem `CommandLineOption` overloads seem to be the cases where I use this constructor:

```C++
    CommandLineOption(
        std::function<void(bool is_set)> callback,
        std::string const& option,
        std::string const& description);
```

... and the error messages go away if I use instead this one:

```
    CommandLineOption(
        std::function<void(bool value)> callback,
        std::string const& option,
        std::string const& description,
        bool default_value);
```

(which can be made equivalent by just specifying a `default_value` of `false`).

Again, I guess this must be down to some kind of stricter checking by g++ 7, although it's not entirely obvious from the release notes: https://gcc.gnu.org/gcc-7/changes.html

@AlanGriffiths any thoughts from your side?  It feels a bit worrying that one can't freely use both constructor choices (unless there's some other C++ subtlety I'm missing that is causing the ambiguity).

**Comment by WebDrake** [comment]
Anyway, I've pushed a bunch of fixup patches that address these issues.  Assuming this passes CI I can squash.

**Comment by WebDrake** [comment]
OK, so, with it passing CI (I'll squash tomorrow, for now I'll leave the fixup patches for inspection), a couple of questions:

* what tests are currently run by the CI?  (I'm not sure that `ctest` is even being run in the current build.)

* what other kind of testing is typical in UBPorts for this part of the stack?

No worries if the answer is "none and none", just want to understand where things sit right now.

**Comment by WebDrake** [comment]
> (which can be made equivalent by just specifying a `default_value` of `false`).

Hmmm, I'm rusty after not working on the codebase for a while -- this isn't a valid solution, because now it means the flags _require_ an argument (e.g. you'd have to do `--version 1` instead of just `--version`, which is a nonsensical breaking change).  So there needs to be some other way to reliably resolve the ambiguity.

**Comment by WebDrake** [comment]
The 2 latest commits should fix things properly.

**Comment by AlanGriffiths** [comment]
@WebDrake sorry, I don't immediately see the compile error you were asking about. I can infer that it was because of the user defined conversion between the lambda you pass and std::function<void(SOMETHING value)> where SOMETHING is not deducible.

I'm not sure how to avoid this. Adding a template constructor could fix a specific case:

```
    template<typename Lambda>
    CommandLineOption(
        Lambda&& callback,
        std::string const& option,
        std::string const& description) :
        CommandLineOption(std::function<void(bool is_set)>(callback), option, description) {}
```
But that conflicts with lambdas that convert to other std::function types. E.g.
```
    template<typename Lambda>
    CommandLineOption(
        Lambda&& callback,
        std::string const& option,
        std::string const& description) :
        CommandLineOption(std::function<void(mir::optional_value<int> const& value)>(callback), option, description) {}
```
If inspiration on how to deduce the argument type of a lambda strikes, I'll try to fix it. Otherwise you're stuck with providing the constructor argument type to explicitly.

**Comment by WebDrake** [comment]
@AlanGriffiths so, just for clarity: I'm raising it not because it's a problem to fix in USC code, but because it seems a bit worrying if code which works just fine with MirAL on xenial can break when being compiled on bionic.

The compiler error suggests it's having difficulty deciding between the constructor overloads that have the form, `CommandLineOption(FunctionType, const string&, const string&)`, i.e. those where the caller provides only a callback, a flag name, and a flag description.

So, for the `--version` flag (note, line numbers are from the code before all the `fixup!` patches):
```
src/main.cpp:150:61: error: call of overloaded ‘CommandLineOption(main(int, char**)::<lambda(bool)>, const char [8], const char [40])’ is ambiguous
         "version", "Show version of Unity System Compositor"));
                                                             ^
In file included from src/main.cpp:28:0:
/usr/include/miral/miral/command_line_option.h:87:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(bool)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
/usr/include/miral/miral/command_line_option.h:82:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(const mir::optional_value<bool>&)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
/usr/include/miral/miral/command_line_option.h:77:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(const mir::optional_value<std::__cxx11::basic_string<char> >&)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
/usr/include/miral/miral/command_line_option.h:72:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(const mir::optional_value<int>&)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
src/main.cpp:141:25: error: ‘pre_init’ was not declared in this scope
     auto version_flag = pre_init(miral::CommandLineOption(
                         ^~~~~~~~
```

... and similarly for the `--debug-without-dm` flag:

```
src/main.cpp:318:5: error: call of overloaded ‘CommandLineOption(<brace-enclosed initializer list>)’ is ambiguous
     };
     ^
In file included from src/main.cpp:28:0:
/usr/include/miral/miral/command_line_option.h:87:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(bool)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
/usr/include/miral/miral/command_line_option.h:82:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(const mir::optional_value<bool>&)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
/usr/include/miral/miral/command_line_option.h:77:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(const mir::optional_value<std::__cxx11::basic_string<char> >&)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
/usr/include/miral/miral/command_line_option.h:72:5: note: candidate: miral::CommandLineOption::CommandLineOption(std::function<void(const mir::optional_value<int>&)>, const string&, const string&)
     CommandLineOption(
     ^~~~~~~~~~~~~~~~~
```

I'm a bit baffled as to _why_ the compiler would see an ambiguity here, TBH, because those resolutions look like they ought to be straightforward.  But this could be me being rusty on C++ templates (most of my development these days is in D, where the template metaprogramming is a lot cleaner and simpler).

There's also an objection to using `pre_init` without the `miral::` prefix:

```
src/main.cpp:141:25: error: ‘pre_init’ was not declared in this scope
     auto version_flag = pre_init(miral::CommandLineOption(
                         ^~~~~~~~
src/main.cpp:141:25: note: suggested alternative:
In file included from src/main.cpp:28:0:
/usr/include/miral/miral/command_line_option.h:111:6: note:   ‘miral::pre_init’
```

... but that seems fair enough: that should probably never have resolved, and it's probably a compiler bug that it did.

**Comment by AlanGriffiths** [comment]
Yes, I realize this isn't blocking you.

I do feel there ought to be a way to get from a lambda to a function<> with the corresponding signature. But this isn't a context in which C++ can deduce it. Maybe I'll wake up with a solution tomorrow. ;)

**Comment by WebDrake** [comment]
For the record: I just tried installing `g++-5` on my bionic system and building with it: `cmake -DCMAKE_CXX_COMPILER=g++-5`.

It fails with the same errors.  So it's not a change of GCC version that is responsible (which is a relief).  I'll try to reduce to a minimal example and file an issue against Mir(AL) on Launchpad.

**Comment by WebDrake** [comment]
On a more positive note: @mariogrip and colleagues -- could we discuss what might be the best way to start moving on getting these changes into UBPorts and rigorously tested?

When working with Yunit I was able to test all of these changes on my own Unity8 desktop install, but I did not test with any devices, and I understand this is where things tend to be most tricky to get right.

Ideally I'd like to break things down into a steady sequence of incremental PRs.  I don't mind at all if this takes a lot of time or needs to be delayed until shorter-term priorities are dealt with, but I'd like to understand your preferences/priorities in managing this sort of change.

**Comment by WebDrake** [comment]
Ping on

> @mariogrip and colleagues -- could we discuss what might be the best way to start moving on getting these changes into UBPorts and rigorously tested?

... ?

**Comment by WebDrake** [comment]
I've squashed down the patches.  Ping on that feedback request? :-)

**Comment by WebDrake** [comment]
Updated to remove manual `std::function<void(bool)>` uses:

```diff
diff --git a/src/main.cpp b/src/main.cpp
index 95689ee..46fc9c0 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -139,14 +139,14 @@ try
     auto const config = std::make_shared<mir::Server>();
 
     auto version_flag = miral::pre_init(miral::CommandLineOption(
-        std::function<void(bool)>([](bool is_set)
+        [](bool is_set)
         {
             if (is_set)
             {
                 std::cerr << "unity-system-compositor " << USC_VERSION << std::endl;
                 exit(EXIT_SUCCESS);
             }
-        }),
+        },
         "version",
         "Show version of Unity System Compositor"));
 
@@ -297,7 +297,7 @@ try
     std::shared_ptr<usc::DMConnection> dm_connection;
 
     miral::CommandLineOption debug_without_dm_flag{
-        std::function<void(bool)>([&](bool debug_without_dm)
+        [&](bool debug_without_dm)
         {
             dm_connection = create_dm_connection(
                                 from_dm_fd,
@@ -313,7 +313,7 @@ try
                 std::cerr << "Unable to chmod socket file " << socket_file << ": " << strerror(errno) << std::endl;
 
             dm_connection->start();
-        }),
+        },
         "debug-without-dm",
         "Run without a display manager (only useful when debugging)"
     };
```

**Comment by WebDrake** [comment]
This will probably fail for now but will pass once new packages are available based on https://github.com/ubports/mir/pull/5 (I've verified this locally on bionic using packages from the Jenkins builds).

**Comment by WebDrake** [comment]
This should now work with the latest ubports mir package (I've tested it successfully locally).  Is there a a way to trigger a fresh build?  I'm going to say, test this please Jenkins, just to see if it works ;-P

**Comment by WebDrake** [comment]
@AlanGriffiths just to check in, what exactly changed in the miral API that caused the major version bump?  This code seems to rebuild as-is without any alterations.

**Comment by AlanGriffiths** [comment]
@WebDrake there were a number of "addenda" interfaces that had functions we couldn't add to WindowManagementPolicy without breaking ABI (vtab changes). Those got merged into WindowManagementPolicy. (I don't think this code touched any of that.)

**Comment by WebDrake** [comment]
I've made some small tweaks to the `CommandLine` related patches, taking full advantage of the improved lambda support.  Will try to come back to some more in-depth work as soon as possible.

**Comment by WebDrake** [comment]
The overall diff:

```diff
diff --git a/src/main.cpp b/src/main.cpp
index 46fc9c0..5c567fb 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -257,28 +257,20 @@ try
     mir::optional_value<int> to_dm_fd;
     std::string debug_active_session_name;
 
-    typedef std::function<void(mir::optional_value<int> const&)> FdCallback_t;
-
-    FdCallback_t from_dm_fd_callback =
+    auto from_dm_fd_flag = miral::pre_init(miral::CommandLineOption(
         [&](mir::optional_value<int> const& from_dm_file_descriptor)
         {
             from_dm_fd = from_dm_file_descriptor;
-        };
-
-    FdCallback_t to_dm_fd_callback =
-        [&](mir::optional_value<int> const& to_dm_file_descriptor)
-        {
-            to_dm_fd = to_dm_file_descriptor;
-        };
-
-    auto from_dm_fd_flag = miral::pre_init(miral::CommandLineOption(
-        from_dm_fd_callback,
+        },
         "from-dm-fd",
         "File descriptor of read end of pipe from display manager [int]"));
     from_dm_fd_flag(*config);
 
     auto to_dm_fd_flag = miral::pre_init(miral::CommandLineOption(
-        to_dm_fd_callback,
+        [&](mir::optional_value<int> const& to_dm_file_descriptor)
+        {
+            to_dm_fd = to_dm_file_descriptor;
+        },
         "to-dm-fd",
         "File descriptor of write end of pipe to display manager [int]"));
     to_dm_fd_flag(*config);
```

**Comment by UniversalSuperBox** [comment]
@WebDrake are you still around and available to continue working on this?

**Comment by WebDrake** [comment]
Hey there.  I'm sorry for the radio silence -- this last 6 months has been a lot busier than I anticipated :-\

If someone else wants to pick this up and run with it -- go for it.  I'm sure I'll try to make time for it at some point but I really am not in a position to promise any time soon.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your PR is now migrated to:
https://gitlab.com/ubports/core/lomiri-system-compositor/-/merge_requests/4

Sorry for your inconvenience.

**Pull request closed without merging**
